# Mandatory settings

name: Chalk
paginate: 25
url: http://chalk.nielsenramon.com
blog_theme: light

# Optional settings

discus_identifier: chalk-1
ga_analytics: UA-28631876-6
rss_enabled: true
local_fonts: false # Change to true if you wish to use local fonts
about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
scrollappear_enabled: true # Change to false to disable
social:
  dribbble: https://dribbble.com/nielsenramon
  facebook: # Add your Facebook link
  github: https://github.com/nielsenramon
  linkedin: # Add your LinkedIn link
  twitter: nielsenramon
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
